import { useState } from "react";
import type { PoolProps, tableData } from "../../types/inbox.types";
import { Box, List, Paper, Typography } from "@mui/material";
import {
  InboxIcon,
  KeyRightArrowIcon,
  MenuIcon,
  TaskIcon,
} from "../../icons/Icons";
import { columnFlex, hoverSx, selectedSx } from "../../utils/styles";

const workPools = ["1st UW Pool", "Sr. UW Pool", "CMO Pool"];
const roleMap: Record<string, string> = {
  "1st UW Pool": "1st UW",
  "Sr. UW Pool": "Sr. UW",
  "CMO Pool": "CMO UW",
};

const sectionTitleSx = {
  color: "#5D5D5D",
  fontWeight: 800,
  pl: 2,
  pb: 1,
  textTransform: "uppercase",
};

type PoolItemProps = {
  label: string;
  value: string;
  selectedPool: string;
  onClick: (val: string) => void;
  count: number;
};

// const data = [
//     {
//       "id": 1,
//       "applicationNo": "OB25175112",
//       "appliedSa": "5000000",
//       "annualPremium": 100000,
//       "productType": "Savings",
//       "drc": "Medium",
//       "hniFlag": "Yes",
//       "isMedical": "Medical",
//       "ptlr": "Low",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "1st UW",
//       "poolTAT": "0-1",
//       "dateAndTimeStamp": "01/01/2026, 0900hrs"
//     },
//     {
//       "id": 2,
//       "applicationNo": "OB25175113",
//       "appliedSa": "3000000",
//       "annualPremium": 60000,
//       "productType": "Term",
//       "drc": "High",
//       "hniFlag": "No",
//       "isMedical": "Non-Medical",
//       "ptlr": "High",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "1st UW",
//       "poolTAT": "1-2",
//       "dateAndTimeStamp": "03/01/2026, 1015hrs"
//     },
//     {
//       "id": 3,
//       "applicationNo": "OB25175114",
//       "appliedSa": "7000000",
//       "annualPremium": 150000,
//       "productType": "Savings",
//       "drc": "Low",
//       "hniFlag": "Yes",
//       "isMedical": "Medical",
//       "ptlr": "Medium",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "Sr. UW",
//       "poolTAT": "2-3",
//       "dateAndTimeStamp": "05/01/2026, 1145hrs"
//     },
//     {
//       "id": 4,
//       "applicationNo": "OB25175115",
//       "appliedSa": "2000000",
//       "annualPremium": 40000,
//       "productType": "Term",
//       "drc": "Medium",
//       "hniFlag": "No",
//       "isMedical": "Non-Medical",
//       "ptlr": "Low",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "Sr. UW",
//       "poolTAT": "3-4",
//       "dateAndTimeStamp": "07/01/2026, 1230hrs"
//     },
//     {
//       "id": 5,
//       "applicationNo": "OB25175116",
//       "appliedSa": "7000000",
//       "annualPremium": "70000",
//       "productType": "Term",
//       "drc": "High",
//       "hniFlag": "Yes",
//       "isMedical": "Non-Medical",
//       "ptlr": "High",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "1st UW",
//       "poolTAT": "0-1",
//       "dateAndTimeStamp": "10/01/2026, 1340hrs"
//     },

//     {
//       "id": 6,
//       "applicationNo": "OB25175121",
//       "appliedSa": "5000000",
//       "annualPremium": 100000,
//       "productType": "Savings",
//       "drc": "Low",
//       "hniFlag": "Yes",
//       "isMedical": "Medical",
//       "ptlr": "Low",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "CMO UW",
//       "poolTAT": "1-2",
//       "dateAndTimeStamp": "12/01/2026, 1420hrs"
//     },

//     {
//       "id": 7,
//       "applicationNo": "OB25175123",
//       "appliedSa": "3000000",
//       "annualPremium": 60000,
//       "productType": "Term",
//       "drc": "Medium",
//       "hniFlag": "No",
//       "isMedical": "Non-Medical",
//       "ptlr": "High",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "CMO UW",
//       "poolTAT": "2-3",
//       "dateAndTimeStamp": "15/01/2026, 1530hrs"
//     },

//     {
//       "id": 8,
//       "applicationNo": "OB25175124",
//       "appliedSa": "7000000",
//       "annualPremium": 150000,
//       "productType": "Savings",
//       "drc": "Medium",
//       "hniFlag": "Yes",
//       "isMedical": "Medical",
//       "ptlr": "Medium",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "CMO UW",
//       "poolTAT": "3-4",
//       "dateAndTimeStamp": "18/01/2026, 1605hrs"
//     },

//     {
//       "id": 9,
//       "applicationNo": "OB25175125",
//       "appliedSa": "2000000",
//       "annualPremium": 40000,
//       "productType": "Term",
//       "drc": "Medium",
//       "hniFlag": "No",
//       "isMedical": "Non-Medical",
//       "ptlr": "Low",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "Sr. UW",
//       "poolTAT": "0-1",
//       "dateAndTimeStamp": "21/01/2026, 1710hrs"
//     },

//     {
//       "id": 10,
//       "applicationNo": "OB25175126",
//       "appliedSa": "7000000",
//       "annualPremium": 70000,
//       "productType": "Term",
//       "drc": "High",
//       "hniFlag": "Yes",
//       "isMedical": "Non-Medical",
//       "ptlr": "High",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "Sr. UW",
//       "poolTAT": "1-2",
//       "dateAndTimeStamp": "25/01/2026, 1800hrs"
//     },

//     {
//       "id": 11,
//       "applicationNo": "OB25175127",
//       "appliedSa": "2000000",
//       "annualPremium": 50000,
//       "productType": "Savings",
//       "drc": "Low",
//       "hniFlag": "Yes",
//       "isMedical": "Medical",
//       "ptlr": "Low",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "1st UW",
//       "poolTAT": "2-3",
//       "dateAndTimeStamp": "02/02/2026, 0915hrs"
//     },

//     {
//       "id": 12,
//       "applicationNo": "OB25175128",
//       "appliedSa": "3000000",
//       "annualPremium": 60000,
//       "productType": "Term",
//       "drc": "Medium",
//       "hniFlag": "No",
//       "isMedical": "Non-Medical",
//       "ptlr": "Medium",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "Sr. UW",
//       "poolTAT": "3-4",
//       "dateAndTimeStamp": "04/02/2026, 1010hrs"
//     },

//     {
//       "id": 13,
//       "applicationNo": "OB25175129",
//       "appliedSa": "5000000",
//       "annualPremium": 100000,
//       "productType": "Savings",
//       "drc": "High",
//       "hniFlag": "Yes",
//       "isMedical": "Medical",
//       "ptlr": "High",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "CMO UW",
//       "poolTAT": "0-1",
//       "dateAndTimeStamp": "06/02/2026, 1125hrs"
//     },

//     {
//       "id": 14,
//       "applicationNo": "OB25175130",
//       "appliedSa": "7000000",
//       "annualPremium": 70000,
//       "productType": "Term",
//       "drc": "Low",
//       "hniFlag": "No",
//       "isMedical": "Non-Medical",
//       "ptlr": "Low",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "1st UW",
//       "poolTAT": "1-2",
//       "dateAndTimeStamp": "08/02/2026, 1235hrs"
//     },

//     {
//       "id": 15,
//       "applicationNo": "OB25175131",
//       "appliedSa": "2000000",
//       "annualPremium": 50000,
//       "productType": "Savings",
//       "drc": "Medium",
//       "hniFlag": "Yes",
//       "isMedical": "Medical",
//       "ptlr": "Medium",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "Sr. UW",
//       "poolTAT": "2-3",
//       "dateAndTimeStamp": "10/02/2026, 1340hrs"
//     },

//     {
//       "id": 16,
//       "applicationNo": "OB25175132",
//       "appliedSa": "3000000",
//       "annualPremium": 60000,
//       "productType": "Term",
//       "drc": "High",
//       "hniFlag": "No",
//       "isMedical": "Non-Medical",
//       "ptlr": "High",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "CMO UW",
//       "poolTAT": "3-4",
//       "dateAndTimeStamp": "12/02/2026, 1450hrs"
//     },

//     {
//       "id": 17,
//       "applicationNo": "OB25175133",
//       "appliedSa": "5000000",
//       "annualPremium": 100000,
//       "productType": "Savings",
//       "drc": "Low",
//       "hniFlag": "Yes",
//       "isMedical": "Medical",
//       "ptlr": "Low",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "1st UW",
//       "poolTAT": "0-1",
//       "dateAndTimeStamp": "14/02/2026, 1515hrs"
//     },

//     {
//       "id": 18,
//       "applicationNo": "OB25175134",
//       "appliedSa": "7000000",
//       "annualPremium": 70000,
//       "productType": "Term",
//       "drc": "Medium",
//       "hniFlag": "No",
//       "isMedical": "Non-Medical",
//       "ptlr": "Medium",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "Sr. UW",
//       "poolTAT": "1-2",
//       "dateAndTimeStamp": "16/02/2026, 1600hrs"
//     },

//     {
//       "id": 19,
//       "applicationNo": "OB25175135",
//       "appliedSa": "2000000",
//       "annualPremium": 50000,
//       "productType": "Savings",
//       "drc": "High",
//       "hniFlag": "Yes",
//       "isMedical": "Medical",
//       "ptlr": "High",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "CMO UW",
//       "poolTAT": "2-3",
//       "dateAndTimeStamp": "18/02/2026, 1710hrs"
//     },

//     {
//       "id": 20,
//       "applicationNo": "OB25175136",
//       "appliedSa": "3000000",
//       "annualPremium": 60000,
//       "productType": "Term",
//       "drc": "Low",
//       "hniFlag": "No",
//       "isMedical": "Non-Medical",
//       "ptlr": "Low",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "1st UW",
//       "poolTAT": "3-4",
//       "dateAndTimeStamp": "20/02/2026, 1800hrs"
//     },
//     {
//       "id": 21,
//       "applicationNo": "OB25175137",
//       "appliedSa": "5000000",
//       "annualPremium": 90000,
//       "productType": "Savings",
//       "drc": "Medium",
//       "hniFlag": "Yes",
//       "isMedical": "Medical",
//       "ptlr": "Low",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "1st UW",
//       "poolTAT": "0-1",
//       "dateAndTimeStamp": "22/02/2026, 0905hrs"
//     },
//     {
//       "id": 22,
//       "applicationNo": "OB25175138",
//       "appliedSa": "3000000",
//       "annualPremium": 65000,
//       "productType": "Term",
//       "drc": "High",
//       "hniFlag": "No",
//       "isMedical": "Non-Medical",
//       "ptlr": "High",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "Sr. UW",
//       "poolTAT": "1-2",
//       "dateAndTimeStamp": "23/02/2026, 1010hrs"
//     },
//     {
//       "id": 23,
//       "applicationNo": "OB25175139",
//       "appliedSa": "7000000",
//       "annualPremium": 155000,
//       "productType": "Savings",
//       "drc": "Low",
//       "hniFlag": "Yes",
//       "isMedical": "Medical",
//       "ptlr": "Medium",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "CMO UW",
//       "poolTAT": "2-3",
//       "dateAndTimeStamp": "24/02/2026, 1115hrs"
//     },
//     {
//       "id": 24,
//       "applicationNo": "OB25175140",
//       "appliedSa": "2000000",
//       "annualPremium": 45000,
//       "productType": "Term",
//       "drc": "Medium",
//       "hniFlag": "No",
//       "isMedical": "Non-Medical",
//       "ptlr": "Low",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "1st UW",
//       "poolTAT": "3-4",
//       "dateAndTimeStamp": "25/02/2026, 1200hrs"
//     },
//     {
//       "id": 25,
//       "applicationNo": "OB25175141",
//       "appliedSa": "6000000",
//       "annualPremium": 120000,
//       "productType": "Savings",
//       "drc": "High",
//       "hniFlag": "Yes",
//       "isMedical": "Medical",
//       "ptlr": "High",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "Sr. UW",
//       "poolTAT": "0-1",
//       "dateAndTimeStamp": "26/02/2026, 1310hrs"
//     },
//     {
//       "id": 26,
//       "applicationNo": "OB25175142",
//       "appliedSa": "4000000",
//       "annualPremium": 80000,
//       "productType": "Term",
//       "drc": "Low",
//       "hniFlag": "No",
//       "isMedical": "Non-Medical",
//       "ptlr": "Medium",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "CMO UW",
//       "poolTAT": "1-2",
//       "dateAndTimeStamp": "27/02/2026, 1405hrs"
//     },
//     {
//       "id": 27,
//       "applicationNo": "OB25175143",
//       "appliedSa": "5000000",
//       "annualPremium": 95000,
//       "productType": "Savings",
//       "drc": "Medium",
//       "hniFlag": "Yes",
//       "isMedical": "Medical",
//       "ptlr": "Low",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "1st UW",
//       "poolTAT": "2-3",
//       "dateAndTimeStamp": "28/02/2026, 1500hrs"
//     },
//     {
//       "id": 28,
//       "applicationNo": "OB25175144",
//       "appliedSa": "3000000",
//       "annualPremium": 70000,
//       "productType": "Term",
//       "drc": "High",
//       "hniFlag": "No",
//       "isMedical": "Non-Medical",
//       "ptlr": "High",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "Sr. UW",
//       "poolTAT": "3-4",
//       "dateAndTimeStamp": "01/03/2026, 1600hrs"
//     },
//     {
//       "id": 29,
//       "applicationNo": "OB25175145",
//       "appliedSa": "7000000",
//       "annualPremium": 160000,
//       "productType": "Savings",
//       "drc": "Low",
//       "hniFlag": "Yes",
//       "isMedical": "Medical",
//       "ptlr": "Medium",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "CMO UW",
//       "poolTAT": "0-1",
//       "dateAndTimeStamp": "02/03/2026, 1705hrs"
//     },
//     {
//       "id": 30,
//       "applicationNo": "OB25175146",
//       "appliedSa": "2000000",
//       "annualPremium": 50000,
//       "productType": "Term",
//       "drc": "Medium",
//       "hniFlag": "No",
//       "isMedical": "Non-Medical",
//       "ptlr": "Low",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "1st UW",
//       "poolTAT": "1-2",
//       "dateAndTimeStamp": "03/03/2026, 1800hrs"
//     },
//     {
//       "id": 31,
//       "applicationNo": "OB25175147",
//       "appliedSa": "5000000",
//       "annualPremium": 100000,
//       "productType": "Savings",
//       "drc": "High",
//       "hniFlag": "Yes",
//       "isMedical": "Medical",
//       "ptlr": "High",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "Sr. UW",
//       "poolTAT": "2-3",
//       "dateAndTimeStamp": "04/03/2026, 0910hrs"
//     },
//     {
//       "id": 32,
//       "applicationNo": "OB25175148",
//       "appliedSa": "3000000",
//       "annualPremium": 60000,
//       "productType": "Term",
//       "drc": "Low",
//       "hniFlag": "No",
//       "isMedical": "Non-Medical",
//       "ptlr": "Low",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "CMO UW",
//       "poolTAT": "3-4",
//       "dateAndTimeStamp": "05/03/2026, 1015hrs"
//     },
//     {
//       "id": 33,
//       "applicationNo": "OB25175149",
//       "appliedSa": "6000000",
//       "annualPremium": 130000,
//       "productType": "Savings",
//       "drc": "Medium",
//       "hniFlag": "Yes",
//       "isMedical": "Medical",
//       "ptlr": "Medium",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "1st UW",
//       "poolTAT": "0-1",
//       "dateAndTimeStamp": "06/03/2026, 1110hrs"
//     },
//     {
//       "id": 34,
//       "applicationNo": "OB25175150",
//       "appliedSa": "4000000",
//       "annualPremium": 85000,
//       "productType": "Term",
//       "drc": "High",
//       "hniFlag": "No",
//       "isMedical": "Non-Medical",
//       "ptlr": "High",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "Sr. UW",
//       "poolTAT": "1-2",
//       "dateAndTimeStamp": "07/03/2026, 1215hrs"
//     },
//     {
//       "id": 35,
//       "applicationNo": "OB25175151",
//       "appliedSa": "7000000",
//       "annualPremium": 170000,
//       "productType": "Savings",
//       "drc": "Low",
//       "hniFlag": "Yes",
//       "isMedical": "Medical",
//       "ptlr": "Low",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "CMO UW",
//       "poolTAT": "2-3",
//       "dateAndTimeStamp": "08/03/2026, 1315hrs"
//     },
//     {
//       "id": 36,
//       "applicationNo": "OB25175152",
//       "appliedSa": "2000000",
//       "annualPremium": 55000,
//       "productType": "Term",
//       "drc": "Medium",
//       "hniFlag": "No",
//       "isMedical": "Non-Medical",
//       "ptlr": "Low",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "1st UW",
//       "poolTAT": "3-4",
//       "dateAndTimeStamp": "09/03/2026, 1410hrs"
//     },
//     {
//       "id": 37,
//       "applicationNo": "OB25175153",
//       "appliedSa": "5000000",
//       "annualPremium": 105000,
//       "productType": "Savings",
//       "drc": "High",
//       "hniFlag": "Yes",
//       "isMedical": "Medical",
//       "ptlr": "High",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "Sr. UW",
//       "poolTAT": "0-1",
//       "dateAndTimeStamp": "10/03/2026, 1510hrs"
//     },
//     {
//       "id": 38,
//       "applicationNo": "OB25175154",
//       "appliedSa": "3000000",
//       "annualPremium": 62000,
//       "productType": "Term",
//       "drc": "Low",
//       "hniFlag": "No",
//       "isMedical": "Non-Medical",
//       "ptlr": "Medium",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "CMO UW",
//       "poolTAT": "1-2",
//       "dateAndTimeStamp": "11/03/2026, 1605hrs"
//     },
//     {
//       "id": 39,
//       "applicationNo": "OB25175155",
//       "appliedSa": "6000000",
//       "annualPremium": 125000,
//       "productType": "Savings",
//       "drc": "Medium",
//       "hniFlag": "Yes",
//       "isMedical": "Medical",
//       "ptlr": "Medium",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "1st UW",
//       "poolTAT": "2-3",
//       "dateAndTimeStamp": "12/03/2026, 1700hrs"
//     },
//     {
//       "id": 40,
//       "applicationNo": "OB25175156",
//       "appliedSa": "4000000",
//       "annualPremium": 90000,
//       "productType": "Term",
//       "drc": "High",
//       "hniFlag": "No",
//       "isMedical": "Non-Medical",
//       "ptlr": "High",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "Sr. UW",
//       "poolTAT": "3-4",
//       "dateAndTimeStamp": "13/03/2026, 1800hrs"
//     },
//     {
//       "id": 41,
//       "applicationNo": "OB25175157",
//       "appliedSa": "7000000",
//       "annualPremium": 180000,
//       "productType": "Savings",
//       "drc": "Low",
//       "hniFlag": "Yes",
//       "isMedical": "Medical",
//       "ptlr": "Low",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "CMO UW",
//       "poolTAT": "0-1",
//       "dateAndTimeStamp": "14/03/2026, 0900hrs"
//     },
//     {
//       "id": 42,
//       "applicationNo": "OB25175158",
//       "appliedSa": "2000000",
//       "annualPremium": 48000,
//       "productType": "Term",
//       "drc": "Medium",
//       "hniFlag": "No",
//       "isMedical": "Non-Medical",
//       "ptlr": "Low",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "1st UW",
//       "poolTAT": "1-2",
//       "dateAndTimeStamp": "15/03/2026, 1000hrs"
//     },
//     {
//       "id": 43,
//       "applicationNo": "OB25175159",
//       "appliedSa": "5000000",
//       "annualPremium": 110000,
//       "productType": "Savings",
//       "drc": "High",
//       "hniFlag": "Yes",
//       "isMedical": "Medical",
//       "ptlr": "High",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "Sr. UW",
//       "poolTAT": "2-3",
//       "dateAndTimeStamp": "16/03/2026, 1105hrs"
//     },
//     {
//       "id": 44,
//       "applicationNo": "OB25175160",
//       "appliedSa": "3000000",
//       "annualPremium": 64000,
//       "productType": "Term",
//       "drc": "Low",
//       "hniFlag": "No",
//       "isMedical": "Non-Medical",
//       "ptlr": "Medium",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "CMO UW",
//       "poolTAT": "3-4",
//       "dateAndTimeStamp": "17/03/2026, 1200hrs"
//     },
//     {
//       "id": 45,
//       "applicationNo": "OB25175161",
//       "appliedSa": "6000000",
//       "annualPremium": 135000,
//       "productType": "Savings",
//       "drc": "Medium",
//       "hniFlag": "Yes",
//       "isMedical": "Medical",
//       "ptlr": "Medium",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "1st UW",
//       "poolTAT": "0-1",
//       "dateAndTimeStamp": "18/03/2026, 1300hrs"
//     },
//     {
//       "id": 46,
//       "applicationNo": "OB25175162",
//       "appliedSa": "4000000",
//       "annualPremium": 92000,
//       "productType": "Term",
//       "drc": "High",
//       "hniFlag": "No",
//       "isMedical": "Non-Medical",
//       "ptlr": "High",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "Sr. UW",
//       "poolTAT": "1-2",
//       "dateAndTimeStamp": "19/03/2026, 1400hrs"
//     },
//     {
//       "id": 47,
//       "applicationNo": "OB25175163",
//       "appliedSa": "7000000",
//       "annualPremium": 190000,
//       "productType": "Savings",
//       "drc": "Low",
//       "hniFlag": "Yes",
//       "isMedical": "Medical",
//       "ptlr": "Low",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "CMO UW",
//       "poolTAT": "2-3",
//       "dateAndTimeStamp": "20/03/2026, 1500hrs"
//     },
//     {
//       "id": 48,
//       "applicationNo": "OB25175164",
//       "appliedSa": "2000000",
//       "annualPremium": 52000,
//       "productType": "Term",
//       "drc": "Medium",
//       "hniFlag": "No",
//       "isMedical": "Non-Medical",
//       "ptlr": "Low",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "1st UW",
//       "poolTAT": "3-4",
//       "dateAndTimeStamp": "21/03/2026, 1600hrs"
//     },
//     {
//       "id": 49,
//       "applicationNo": "OB25175165",
//       "appliedSa": "5000000",
//       "annualPremium": 115000,
//       "productType": "Savings",
//       "drc": "High",
//       "hniFlag": "Yes",
//       "isMedical": "Medical",
//       "ptlr": "High",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "Sr. UW",
//       "poolTAT": "0-1",
//       "dateAndTimeStamp": "22/03/2026, 1700hrs"
//     },
//     {
//       "id": 50,
//       "applicationNo": "OB25175166",
//       "appliedSa": "3000000",
//       "annualPremium": 68000,
//       "productType": "Term",
//       "drc": "Low",
//       "hniFlag": "No",
//       "isMedical": "Non-Medical",
//       "ptlr": "Medium",
//       "breDecision": "Standard",
//       "channel": "BOL",
//       "munichReMedicalDecision": "Standard",
//       "roleType": "CMO UW",
//       "poolTAT": "1-2",
//       "dateAndTimeStamp": "23/03/2026, 1800hrs"
//     }
// ]
const data = [
  {
    id: 1,
    applicationNo: "OB25175112",
    appliedSa: "5000000",
    annualPremium: 100000,
    productType: "Savings",
    drc: "Medium",
    hniFlag: "Yes",
    isMedical: "Medical",
    ptlr: "Low",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "1st UW",
    poolTAT: "0-1",
    dateAndTimeStamp: "01/01/2026, 0900hrs",
  },
  {
    id: 2,
    applicationNo: "OB25175113",
    appliedSa: "3000000",
    annualPremium: 60000,
    productType: "Term",
    drc: "High",
    hniFlag: "No",
    isMedical: "Non-Medical",
    ptlr: "High",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "1st UW",
    poolTAT: "1-2",
    dateAndTimeStamp: "03/01/2026, 1015hrs",
  },
  {
    id: 3,
    applicationNo: "OB25175114",
    appliedSa: "7000000",
    annualPremium: 150000,
    productType: "Savings",
    drc: "Low",
    hniFlag: "Yes",
    isMedical: "Medical",
    ptlr: "Medium",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "Sr. UW",
    poolTAT: "2-3",
    dateAndTimeStamp: "05/01/2026, 1145hrs",
  },
  {
    id: 4,
    applicationNo: "OB25175115",
    appliedSa: "2000000",
    annualPremium: 40000,
    productType: "Term",
    drc: "Medium",
    hniFlag: "No",
    isMedical: "Non-Medical",
    ptlr: "Low",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "Sr. UW",
    poolTAT: "3-4",
    dateAndTimeStamp: "07/01/2026, 1230hrs",
  },
  {
    id: 5,
    applicationNo: "OB25175116",
    appliedSa: "7000000",
    annualPremium: 70000,
    productType: "Term",
    drc: "High",
    hniFlag: "Yes",
    isMedical: "Non-Medical",
    ptlr: "High",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "1st UW",
    poolTAT: "0-1",
    dateAndTimeStamp: "10/01/2026, 1340hrs",
  },

  {
    id: 6,
    applicationNo: "OB25175121",
    appliedSa: "5000000",
    annualPremium: 100000,
    productType: "Savings",
    drc: "Low",
    hniFlag: "Yes",
    isMedical: "Medical",
    ptlr: "Low",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "CMO UW",
    poolTAT: "1-2",
    dateAndTimeStamp: "12/01/2026, 1420hrs",
  },

  {
    id: 7,
    applicationNo: "OB25175123",
    appliedSa: "3000000",
    annualPremium: 60000,
    productType: "Term",
    drc: "Medium",
    hniFlag: "No",
    isMedical: "Non-Medical",
    ptlr: "High",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "CMO UW",
    poolTAT: "2-3",
    dateAndTimeStamp: "15/01/2026, 1530hrs",
  },

  {
    id: 8,
    applicationNo: "OB25175124",
    appliedSa: "7000000",
    annualPremium: 150000,
    productType: "Savings",
    drc: "Medium",
    hniFlag: "Yes",
    isMedical: "Medical",
    ptlr: "Medium",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "CMO UW",
    poolTAT: "3-4",
    dateAndTimeStamp: "18/01/2026, 1605hrs",
  },

  {
    id: 9,
    applicationNo: "OB25175125",
    appliedSa: "2000000",
    annualPremium: 40000,
    productType: "Term",
    drc: "Medium",
    hniFlag: "No",
    isMedical: "Non-Medical",
    ptlr: "Low",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "Sr. UW",
    poolTAT: "0-1",
    dateAndTimeStamp: "21/01/2026, 1710hrs",
  },

  {
    id: 10,
    applicationNo: "OB25175126",
    appliedSa: "7000000",
    annualPremium: 70000,
    productType: "Term",
    drc: "High",
    hniFlag: "Yes",
    isMedical: "Non-Medical",
    ptlr: "High",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "Sr. UW",
    poolTAT: "1-2",
    dateAndTimeStamp: "25/01/2026, 1800hrs",
  },

  {
    id: 11,
    applicationNo: "OB25175127",
    appliedSa: "2000000",
    annualPremium: 50000,
    productType: "Savings",
    drc: "Low",
    hniFlag: "Yes",
    isMedical: "Medical",
    ptlr: "Low",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "1st UW",
    poolTAT: "2-3",
    dateAndTimeStamp: "02/02/2026, 0915hrs",
  },

  {
    id: 12,
    applicationNo: "OB25175128",
    appliedSa: "3000000",
    annualPremium: 60000,
    productType: "Term",
    drc: "Medium",
    hniFlag: "No",
    isMedical: "Non-Medical",
    ptlr: "Medium",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "Sr. UW",
    poolTAT: "3-4",
    dateAndTimeStamp: "04/02/2026, 1010hrs",
  },

  {
    id: 13,
    applicationNo: "OB25175129",
    appliedSa: "5000000",
    annualPremium: 100000,
    productType: "Savings",
    drc: "High",
    hniFlag: "Yes",
    isMedical: "Medical",
    ptlr: "High",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "CMO UW",
    poolTAT: "0-1",
    dateAndTimeStamp: "06/02/2026, 1125hrs",
  },

  {
    id: 14,
    applicationNo: "OB25175130",
    appliedSa: "7000000",
    annualPremium: 70000,
    productType: "Term",
    drc: "Low",
    hniFlag: "No",
    isMedical: "Non-Medical",
    ptlr: "Low",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "1st UW",
    poolTAT: "1-2",
    dateAndTimeStamp: "08/02/2026, 1235hrs",
  },

  {
    id: 15,
    applicationNo: "OB25175131",
    appliedSa: "2000000",
    annualPremium: 50000,
    productType: "Savings",
    drc: "Medium",
    hniFlag: "Yes",
    isMedical: "Medical",
    ptlr: "Medium",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "Sr. UW",
    poolTAT: "2-3",
    dateAndTimeStamp: "10/02/2026, 1340hrs",
  },

  {
    id: 16,
    applicationNo: "OB25175132",
    appliedSa: "3000000",
    annualPremium: 60000,
    productType: "Term",
    drc: "High",
    hniFlag: "No",
    isMedical: "Non-Medical",
    ptlr: "High",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "CMO UW",
    poolTAT: "3-4",
    dateAndTimeStamp: "12/02/2026, 1450hrs",
  },

  {
    id: 17,
    applicationNo: "OB25175133",
    appliedSa: "5000000",
    annualPremium: 100000,
    productType: "Savings",
    drc: "Low",
    hniFlag: "Yes",
    isMedical: "Medical",
    ptlr: "Low",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "1st UW",
    poolTAT: "0-1",
    dateAndTimeStamp: "14/02/2026, 1515hrs",
  },

  {
    id: 18,
    applicationNo: "OB25175134",
    appliedSa: "7000000",
    annualPremium: 70000,
    productType: "Term",
    drc: "Medium",
    hniFlag: "No",
    isMedical: "Non-Medical",
    ptlr: "Medium",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "Sr. UW",
    poolTAT: "1-2",
    dateAndTimeStamp: "16/02/2026, 1600hrs",
  },

  {
    id: 19,
    applicationNo: "OB25175135",
    appliedSa: "2000000",
    annualPremium: 50000,
    productType: "Savings",
    drc: "High",
    hniFlag: "Yes",
    isMedical: "Medical",
    ptlr: "High",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "CMO UW",
    poolTAT: "2-3",
    dateAndTimeStamp: "18/02/2026, 1710hrs",
  },

  {
    id: 20,
    applicationNo: "OB25175136",
    appliedSa: "3000000",
    annualPremium: 60000,
    productType: "Term",
    drc: "Low",
    hniFlag: "No",
    isMedical: "Non-Medical",
    ptlr: "Low",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "1st UW",
    poolTAT: "3-4",
    dateAndTimeStamp: "20/02/2026, 1800hrs",
  },
  {
    id: 21,
    applicationNo: "OB25175137",
    appliedSa: "5000000",
    annualPremium: 90000,
    productType: "Savings",
    drc: "Medium",
    hniFlag: "Yes",
    isMedical: "Medical",
    ptlr: "Low",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "1st UW",
    poolTAT: "0-1",
    dateAndTimeStamp: "22/02/2026, 0905hrs",
  },
  {
    id: 22,
    applicationNo: "OB25175138",
    appliedSa: "3000000",
    annualPremium: 65000,
    productType: "Term",
    drc: "High",
    hniFlag: "No",
    isMedical: "Non-Medical",
    ptlr: "High",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "Sr. UW",
    poolTAT: "1-2",
    dateAndTimeStamp: "23/02/2026, 1010hrs",
  },
  {
    id: 23,
    applicationNo: "OB25175139",
    appliedSa: "7000000",
    annualPremium: 155000,
    productType: "Savings",
    drc: "Low",
    hniFlag: "Yes",
    isMedical: "Medical",
    ptlr: "Medium",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "CMO UW",
    poolTAT: "2-3",
    dateAndTimeStamp: "24/02/2026, 1115hrs",
  },
  {
    id: 24,
    applicationNo: "OB25175140",
    appliedSa: "2000000",
    annualPremium: 45000,
    productType: "Term",
    drc: "Medium",
    hniFlag: "No",
    isMedical: "Non-Medical",
    ptlr: "Low",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "1st UW",
    poolTAT: "3-4",
    dateAndTimeStamp: "25/02/2026, 1200hrs",
  },
  {
    id: 25,
    applicationNo: "OB25175141",
    appliedSa: "6000000",
    annualPremium: 120000,
    productType: "Savings",
    drc: "High",
    hniFlag: "Yes",
    isMedical: "Medical",
    ptlr: "High",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "Sr. UW",
    poolTAT: "0-1",
    dateAndTimeStamp: "26/02/2026, 1310hrs",
  },
  {
    id: 26,
    applicationNo: "OB25175142",
    appliedSa: "4000000",
    annualPremium: 80000,
    productType: "Term",
    drc: "Low",
    hniFlag: "No",
    isMedical: "Non-Medical",
    ptlr: "Medium",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "CMO UW",
    poolTAT: "1-2",
    dateAndTimeStamp: "27/02/2026, 1405hrs",
  },
  {
    id: 27,
    applicationNo: "OB25175143",
    appliedSa: "5000000",
    annualPremium: 95000,
    productType: "Savings",
    drc: "Medium",
    hniFlag: "Yes",
    isMedical: "Medical",
    ptlr: "Low",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "1st UW",
    poolTAT: "2-3",
    dateAndTimeStamp: "28/02/2026, 1500hrs",
  },
  {
    id: 28,
    applicationNo: "OB25175144",
    appliedSa: "3000000",
    annualPremium: 70000,
    productType: "Term",
    drc: "High",
    hniFlag: "No",
    isMedical: "Non-Medical",
    ptlr: "High",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "Sr. UW",
    poolTAT: "3-4",
    dateAndTimeStamp: "01/03/2026, 1600hrs",
  },
  {
    id: 29,
    applicationNo: "OB25175145",
    appliedSa: "7000000",
    annualPremium: 160000,
    productType: "Savings",
    drc: "Low",
    hniFlag: "Yes",
    isMedical: "Medical",
    ptlr: "Medium",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "CMO UW",
    poolTAT: "0-1",
    dateAndTimeStamp: "02/03/2026, 1705hrs",
  },
  {
    id: 30,
    applicationNo: "OB25175146",
    appliedSa: "2000000",
    annualPremium: 50000,
    productType: "Term",
    drc: "Medium",
    hniFlag: "No",
    isMedical: "Non-Medical",
    ptlr: "Low",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "1st UW",
    poolTAT: "1-2",
    dateAndTimeStamp: "03/03/2026, 1800hrs",
  },
  {
    id: 31,
    applicationNo: "OB25175147",
    appliedSa: "5000000",
    annualPremium: 100000,
    productType: "Savings",
    drc: "High",
    hniFlag: "Yes",
    isMedical: "Medical",
    ptlr: "High",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "Sr. UW",
    poolTAT: "2-3",
    dateAndTimeStamp: "04/03/2026, 0910hrs",
  },
  {
    id: 32,
    applicationNo: "OB25175148",
    appliedSa: "3000000",
    annualPremium: 60000,
    productType: "Term",
    drc: "Low",
    hniFlag: "No",
    isMedical: "Non-Medical",
    ptlr: "Low",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "CMO UW",
    poolTAT: "3-4",
    dateAndTimeStamp: "05/03/2026, 1015hrs",
  },
  {
    id: 33,
    applicationNo: "OB25175149",
    appliedSa: "6000000",
    annualPremium: 130000,
    productType: "Savings",
    drc: "Medium",
    hniFlag: "Yes",
    isMedical: "Medical",
    ptlr: "Medium",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "1st UW",
    poolTAT: "0-1",
    dateAndTimeStamp: "06/03/2026, 1110hrs",
  },
  {
    id: 34,
    applicationNo: "OB25175150",
    appliedSa: "4000000",
    annualPremium: 85000,
    productType: "Term",
    drc: "High",
    hniFlag: "No",
    isMedical: "Non-Medical",
    ptlr: "High",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "Sr. UW",
    poolTAT: "1-2",
    dateAndTimeStamp: "07/03/2026, 1215hrs",
  },
  {
    id: 35,
    applicationNo: "OB25175151",
    appliedSa: "7000000",
    annualPremium: 170000,
    productType: "Savings",
    drc: "Low",
    hniFlag: "Yes",
    isMedical: "Medical",
    ptlr: "Low",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "CMO UW",
    poolTAT: "2-3",
    dateAndTimeStamp: "08/03/2026, 1315hrs",
  },
  {
    id: 36,
    applicationNo: "OB25175152",
    appliedSa: "2000000",
    annualPremium: 55000,
    productType: "Term",
    drc: "Medium",
    hniFlag: "No",
    isMedical: "Non-Medical",
    ptlr: "Low",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "1st UW",
    poolTAT: "3-4",
    dateAndTimeStamp: "09/03/2026, 1410hrs",
  },
  {
    id: 37,
    applicationNo: "OB25175153",
    appliedSa: "5000000",
    annualPremium: 105000,
    productType: "Savings",
    drc: "High",
    hniFlag: "Yes",
    isMedical: "Medical",
    ptlr: "High",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "Sr. UW",
    poolTAT: "0-1",
    dateAndTimeStamp: "10/03/2026, 1510hrs",
  },
  {
    id: 38,
    applicationNo: "OB25175154",
    appliedSa: "3000000",
    annualPremium: 62000,
    productType: "Term",
    drc: "Low",
    hniFlag: "No",
    isMedical: "Non-Medical",
    ptlr: "Medium",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "CMO UW",
    poolTAT: "1-2",
    dateAndTimeStamp: "11/03/2026, 1605hrs",
  },
  {
    id: 39,
    applicationNo: "OB25175155",
    appliedSa: "6000000",
    annualPremium: 125000,
    productType: "Savings",
    drc: "Medium",
    hniFlag: "Yes",
    isMedical: "Medical",
    ptlr: "Medium",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "1st UW",
    poolTAT: "2-3",
    dateAndTimeStamp: "12/03/2026, 1700hrs",
  },
  {
    id: 40,
    applicationNo: "OB25175156",
    appliedSa: "4000000",
    annualPremium: 90000,
    productType: "Term",
    drc: "High",
    hniFlag: "No",
    isMedical: "Non-Medical",
    ptlr: "High",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "Sr. UW",
    poolTAT: "3-4",
    dateAndTimeStamp: "13/03/2026, 1800hrs",
  },
  {
    id: 41,
    applicationNo: "OB25175157",
    appliedSa: "7000000",
    annualPremium: 180000,
    productType: "Savings",
    drc: "Low",
    hniFlag: "Yes",
    isMedical: "Medical",
    ptlr: "Low",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "CMO UW",
    poolTAT: "0-1",
    dateAndTimeStamp: "14/03/2026, 0900hrs",
  },
  {
    id: 42,
    applicationNo: "OB25175158",
    appliedSa: "2000000",
    annualPremium: 48000,
    productType: "Term",
    drc: "Medium",
    hniFlag: "No",
    isMedical: "Non-Medical",
    ptlr: "Low",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "1st UW",
    poolTAT: "1-2",
    dateAndTimeStamp: "15/03/2026, 1000hrs",
  },
  {
    id: 43,
    applicationNo: "OB25175159",
    appliedSa: "5000000",
    annualPremium: 110000,
    productType: "Savings",
    drc: "High",
    hniFlag: "Yes",
    isMedical: "Medical",
    ptlr: "High",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "Sr. UW",
    poolTAT: "2-3",
    dateAndTimeStamp: "16/03/2026, 1105hrs",
  },
  {
    id: 44,
    applicationNo: "OB25175160",
    appliedSa: "3000000",
    annualPremium: 64000,
    productType: "Term",
    drc: "Low",
    hniFlag: "No",
    isMedical: "Non-Medical",
    ptlr: "Medium",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "CMO UW",
    poolTAT: "3-4",
    dateAndTimeStamp: "17/03/2026, 1200hrs",
  },
  {
    id: 45,
    applicationNo: "OB25175161",
    appliedSa: "6000000",
    annualPremium: 135000,
    productType: "Savings",
    drc: "Medium",
    hniFlag: "Yes",
    isMedical: "Medical",
    ptlr: "Medium",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "1st UW",
    poolTAT: "0-1",
    dateAndTimeStamp: "18/03/2026, 1300hrs",
  },
  {
    id: 46,
    applicationNo: "OB25175162",
    appliedSa: "4000000",
    annualPremium: 92000,
    productType: "Term",
    drc: "High",
    hniFlag: "No",
    isMedical: "Non-Medical",
    ptlr: "High",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "Sr. UW",
    poolTAT: "1-2",
    dateAndTimeStamp: "19/03/2026, 1400hrs",
  },
  {
    id: 47,
    applicationNo: "OB25175163",
    appliedSa: "7000000",
    annualPremium: 190000,
    productType: "Savings",
    drc: "Low",
    hniFlag: "Yes",
    isMedical: "Medical",
    ptlr: "Low",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "CMO UW",
    poolTAT: "2-3",
    dateAndTimeStamp: "20/03/2026, 1500hrs",
  },
  {
    id: 48,
    applicationNo: "OB25175164",
    appliedSa: "2000000",
    annualPremium: 52000,
    productType: "Term",
    drc: "Medium",
    hniFlag: "No",
    isMedical: "Non-Medical",
    ptlr: "Low",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "1st UW",
    poolTAT: "3-4",
    dateAndTimeStamp: "21/03/2026, 1600hrs",
  },
  {
    id: 49,
    applicationNo: "OB25175165",
    appliedSa: "5000000",
    annualPremium: 115000,
    productType: "Savings",
    drc: "High",
    hniFlag: "Yes",
    isMedical: "Medical",
    ptlr: "High",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "Sr. UW",
    poolTAT: "0-1",
    dateAndTimeStamp: "22/03/2026, 1700hrs",
  },
  {
    id: 50,
    applicationNo: "OB25175166",
    appliedSa: "3000000",
    annualPremium: 68000,
    productType: "Term",
    drc: "Low",
    hniFlag: "No",
    isMedical: "Non-Medical",
    ptlr: "Medium",
    breDecision: "Standard",
    channel: "BOL",
    munichReMedicalDecision: "Standard",
    roleType: "CMO UW",
    poolTAT: "1-2",
    dateAndTimeStamp: "23/03/2026, 1800hrs",
  },
];

const PoolItem = ({
  label,
  value,
  selectedPool,
  onClick,
  count,
}: PoolItemProps) => {
  const isSelected = selectedPool === value;

  return (
    <Box
      onClick={() => onClick(value)}
      sx={{
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        px: 2,
        py: 1.5,
        mb: 1,
        pl: label !== "All Cases" ? 4 : 2,
        ...(isSelected ? selectedSx : hoverSx),
      }}
    >
      <Typography
        sx={{
          fontWeight: 600,
          color: isSelected ? "#9A2529" : "#999999",
        }}
      >
        {label} ({count})
      </Typography>

      {isSelected && <KeyRightArrowIcon style={{ color: "#9A2529" }} />}
    </Box>
  );
};

const LeftPanel = ({
  onSelectPool,
  selectedPool,
  toggle,
  setToggle,
}: PoolProps) => {
  const [rows] = useState<tableData[]>(data);

  const getCount = (pool: string) => {
    if (pool === "All Cases") return rows.length;

    const role = roleMap[pool];
    return rows.filter((row) => row.roleType === role).length;
  };

  return (
    <Box
      sx={{
        width: toggle ? "64px" : "250px",
        backgroundColor: "#fff",
        transition: "all 0.3s",
        overflow: "hidden",
      }}
    >
      <Paper sx={{ height: "100%" }}>
        <Box sx={{ pl: 2, py: 2 }}>
          <Box
            onClick={() => setToggle((prev) => !prev)}
            sx={{ cursor: "pointer" }}
          >
            <MenuIcon />
          </Box>
        </Box>

        {toggle ? (
          <Box
            sx={{
              ...columnFlex,
              gap: 4,
              padding: 2,
            }}
          >
            <InboxIcon />
            <TaskIcon />
          </Box>
        ) : (
          <>
            {/* INBOX */}
            <Typography sx={sectionTitleSx}>inbox</Typography>

            {/* ALL CASES */}
            <PoolItem
              label="All Cases"
              value="All Cases"
              selectedPool={selectedPool}
              onClick={onSelectPool}
              count={getCount("All Cases")}
            />

            {/* WORK POOLS */}

            <Typography sx={sectionTitleSx}>work pools</Typography>

            <List disablePadding>
              {workPools.map((pool) => (
                <PoolItem
                  key={pool}
                  label={roleMap[pool] ?? pool}
                  value={pool}
                  selectedPool={selectedPool}
                  onClick={onSelectPool}
                  count={getCount(pool)}
                />
              ))}
            </List>
          </>
        )}
      </Paper>
    </Box>
  );
};

export default LeftPanel;
